apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-radix-d2
  labels:
    name: parsec-radix-d2
spec:
  template:
    spec:
      containers:
        - image: anakli/cca:splash2x_radix
          name: parsec-radix-d2
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "taskset -c 0,1 ./run -a run -S splash2x -p radix -i native -n 2",
            ]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-d-4core"
