apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-blackscholes-b1
  labels:
    name: parsec-blackscholes-b1
spec:
  template:
    spec:
      containers:
        - image: anakli/cca:parsec_blackscholes
          name: parsec-blackscholes-b1
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "taskset -c 1 ./run -a run -S parsec -p blackscholes -i native -n 1",
            ]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-2core"
