apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-blackscholes-a
  labels:
    name: parsec-blackscholes-a
spec:
  template:
    spec:
      containers:
        - image: anakli/cca:parsec_blackscholes
          name: parsec-blackscholes-a
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "taskset -c 0,1 ./run -a run -S parsec -p blackscholes -i native -n 2",
            ]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-a-2core"
