apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-dedup-c
  labels:
    name: parsec-dedup-c
spec:
  template:
    spec:
      containers:
        - image: anakli/cca:parsec_dedup
          name: parsec-dedup-c
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "taskset -c 0,1,2,3 ./run -a run -S parsec -p dedup -i native -n 4",
            ]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-4core"
