apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-vips-d
  labels:
    name: parsec-vips-d
spec:
  template:
    spec:
      containers:
        - image: anakli/cca:parsec_vips
          name: parsec-vips-d
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "taskset -c 0,1,2,3 ./run -a run -S parsec -p vips -i native -n 4",
            ]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-d-4core"
