apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-vips-b
  labels:
    name: parsec-vips-b
spec:
  template:
    spec:
      containers:
        - image: anakli/cca:parsec_vips
          name: parsec-vips-b
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "taskset -c 0,1 ./run -a run -S parsec -p vips -i native -n 2",
            ]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-2core"
